name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18.x

      - name: Install Dependencies
        run: npm install

      - name: Build Extension
        run: npm run vscode:prepublish

    #   - name: Run Tests
    #     run: npm test

      - name: Package Extension
        run: npx vsce package

    #   - name: Verify Extension
    #     run: npx vscode-test